version = "3.11.4"
runner.dialect = scala3

maxColumn = 100
indent.main = 2
indent.defnSite = 2
indent.caseSite = 2
indent.extendSite = 2
align.preset = some
newlines.source = fold
newlines.avoidForSimpleOverflow = [slc, punct]
newlines.avoidInResultType = true

rewrite.rules = [RedundantParens, SortModifiers, PreferCurlyFors, Imports, RemoveSemicolons]
rewrite.redundantParens.infixSide = some
rewrite.sortModifiers.preset = styleGuide
rewrite.imports.sort = original

docstrings.style = Asterisk
docstrings.removeEmpty = true
docstrings.oneline = fold
docstrings.blankFirstLine = fold
docstrings.forceBlankLineBefore = false