commands:
    showitem:
        show-everyone-message:
            single: "<white><player> <yellow>shows off their [<item>]!"
            plural: "<white><player> <yellow>shows off their <quantity>x [<item>]!"