name: ShowOff
description: Show off your items to your friends!
main: net.lunapixu.showoff.ShowOff
version: 0.2.0
author: LunaPixu
api-version: '1.21.4'
depend: []
commands:
    showitem:
        usage: "/showitem [player]"
        description: Show off the item in your hand!
        permission: showoff.showitem
        permission-message: "You do not have permission to show off"
    reload:
        usage: "/showoff reload"
        description: Reload plugin's configs
        permission: showoff.reload
        permission-message: "You do not have permission to reload the plugin"
permissions:
    showoff.showitem:
      description: Allows you to flex your item in chat via command
      default: notop
    showoff.reload:
      description: Allows you to reload the plugin
      default: op

libraries:
  - org.scala-lang:scala3-library_3:3.7.2